### ISSUE TITLE
Readme file enhancement

### ISSUE THREAD

**Issue by anirudhsai20** [ADRE9/bunk-manager-mern#141]
The Readme file can be enhanced by adding a list of all the Open Source progarms in which this project was listed in.

**Comment by anirudhsai20** [comment]
Hi! Please assign this issue to me under GSSOC.

**Comment by ADRE9** [comment]
Sure Go Ahead!

**Comment by kunaljain0212** [comment]
I feel this is something which a project should flaunt and so I would suggest we should move this section to the top, after the images etc. Also currently the logo of GSSoC is very big, I think we can have consistently sized small square boxes they would look better, since the logo is taking lots of space at the moment. What do you think @ADRE9 ?
